// Escolhe um emoji de acordo com o nome do produto (nicho de feira/mercado).
// Fallback: sacola de compras.
const MAPA: Array<[RegExp, string]> = [
  [/tomate|molho/i, '🍅'],
  [/alface|rúcula|rucula|couve|verdura|salada/i, '🥬'],
  [/batata/i, '🥔'],
  [/cenoura/i, '🥕'],
  [/cebola|alho/i, '🧅'],
  [/milho/i, '🌽'],
  [/piment/i, '🌶️'],
  [/brócolis|brocolis/i, '🥦'],
  [/pepino|abobrinha/i, '🥒'],
  [/cogumelo|champignon/i, '🍄'],
  [/banana/i, '🍌'],
  [/maçã|maca|fuji|gala/i, '🍎'],
  [/uva/i, '🍇'],
  [/laranja|mexerica|tangerina/i, '🍊'],
  [/limão|limao/i, '🍋'],
  [/morango/i, '🍓'],
  [/melancia/i, '🍉'],
  [/abacaxi/i, '🍍'],
  [/manga/i, '🥭'],
  [/pêra|pera|pêssego|pessego/i, '🍐'],
  [/abacate/i, '🥑'],
  [/coco/i, '🥥'],
  [/pão|pao|baguete/i, '🍞'],
  [/croissant/i, '🥐'],
  [/bolo/i, '🍰'],
  [/biscoito|bolacha|cookie/i, '🍪'],
  [/leite/i, '🥛'],
  [/queijo|mussarela|muçarela/i, '🧀'],
  [/ovo/i, '🥚'],
  [/manteiga/i, '🧈'],
  [/carne|bife|patinho|alcatra|picanha/i, '🥩'],
  [/frango|galinha|peito/i, '🍗'],
  [/bacon|toucinho/i, '🥓'],
  [/peixe|salmão|salmao|tilápia|tilapia/i, '🐟'],
  [/camarão|camarao/i, '🦐'],
  [/arroz/i, '🍚'],
  [/feijão|feijao/i, '🫘'],
  [/macarrão|macarrao|massa|espaguete/i, '🍝'],
  [/café|cafe/i, '☕'],
  [/chá|cha\b/i, '🍵'],
  [/açúcar|acucar|mel/i, '🍯'],
  [/sal\b/i, '🧂'],
  [/azeite|óleo|oleo/i, '🫒'],
  [/refrigerante|refri|coca|guaraná|guarana|soda/i, '🥤'],
  [/suco/i, '🧃'],
  [/água|agua/i, '💧'],
  [/cerveja/i, '🍺'],
  [/vinho/i, '🍷'],
  [/chocolate/i, '🍫'],
  [/sorvete/i, '🍨'],
  [/pizza/i, '🍕'],
  [/sabão|sabao|detergent|limpeza|amaciante/i, '🧼'],
  [/papel/i, '🧻'],
]

export function emojiParaProduto(nome: string): string {
  for (const [regex, emoji] of MAPA) {
    if (regex.test(nome)) return emoji
  }
  return '🛍️'
}
